<?php

namespace App\Http\Controllers;

use App\Models\Karier;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Storage;

class KarierController extends Controller
{
    public function index(Request $request)
    {
        $query = Karier::query();

        // Filter by status
        if ($request->has('status') && !empty($request->status)) {
            $query->where('status', $request->status);
        }

        // Order by created_at desc
        $karier = $query->latest()->paginate(10);

        return view('karier.index', compact('karier'));
    }

    public function create()
    {
        return view('karier.create');
    }

    public function store(Request $request)
    {
        $validated = $request->validate([
            'nama_kota' => 'required|string|max:255',
            'posisi' => 'required|string|max:255',
            'email' => 'required|email|max:255',
            'responsibilities' => 'required|string',
            'qualification' => 'required|string',
        ]);

        try {
            // Create the karier record
            Karier::create([
                'nama_kota' => $validated['nama_kota'],
                'posisi' => $validated['posisi'],
                'email' => $validated['email'],
                'responsibilities' => $validated['responsibilities'],
                'qualification' => $validated['qualification'],
                // Slug will be automatically generated by the model's boot method
            ]);

            return redirect()->route('karier.index')
                ->with('success', 'Lowongan berhasil ditambahkan');
                
        } catch (\Exception $e) {
            return redirect()->back()
                ->withInput()
                ->with('error', 'Terjadi kesalahan: ' . $e->getMessage());
        }
    }

    public function show($id)
    {
        $karier = Karier::findOrFail($id);
        return view('karier.show', compact('karier'));
    }

    public function edit($id)
    {
        $karier = Karier::findOrFail($id);
        return view('karier.edit', compact('karier'));
    }

    public function update(Request $request, $id)
    {
        $karier = Karier::findOrFail($id);
        
        $validated = $request->validate([
            'nama_kota' => 'required|string|max:255',
            'posisi' => 'required|string|max:255',
            'email' => 'required|email|max:255',
            'responsibilities' => 'required|string',
            'qualification' => 'required|string',
        ]);

        try {
            $karier->update($validated);
            
            return redirect()->route('karier.index')
                ->with('success', 'Lowongan berhasil diperbarui');
                
        } catch (\Exception $e) {
            return redirect()->back()
                ->withInput()
                ->with('error', 'Terjadi kesalahan: ' . $e->getMessage());
        }
    }

    public function destroy($id)
    {
        $karier = Karier::findOrFail($id);
        
        
        $karier->delete();

        return redirect()->route('karier.index')
            ->with('success', 'Lowongan berhasil dihapus');
    }
}
